title: Sturtz Network Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.sturtz.io
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Sturtz 001
      category: Servers
    - name: Sturtz 002
      category: Servers
    - name: Sturtz 003
      category: Servers
    - name: Sturtz Cloud
      description: Sturtz Cloud - Private File storage
      category: Software
      link: https://cloud.sturtz.io
    - name: Sturtz One
      description: Sturtz Admin Login
      category: Admin
    - name: Sturtz Search
      category: Software
      description: Sturtz Search
      link: https://www.sturtz.io
    - name: VPN
      category: Network
    - name: DNS
      category: Network
    - name: Router
      category: Network
    - name: Proxy
      category: Network
    - name: Filters
      category: Network
    - name: Sturtz Git
      category: Software
      description: Public Software hosting
    - name: S2S
      category: Network
      description: Server to Server Links
    - name: Website Routing
      category: Network
    - name: Firewall
      category: Network
    - name: KyLANRen
      category: WIFI
      description: WIFI Network
    - name: sturtz-network
      description: WIFI Network
      category: WIFI
    - name: sturtz-network-5G
      category: WIFI
      description: WIFI Network
    - name: msturtz
      category: WIFI
      description: WIFI Network
    - name: ITS
      category: Admin
      description: Internal Ticket System
    - name: Radio
      category: Software
    - name: Home
      category: Admin
      description: Home Control
    - name: DHCP
      category: WIFI
      description: IP/Subnet assignment
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: false
  headerTextColor: white
  logo: /img/logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Servers
      description: Main Hardware
      closed: true
    - name: Software
      closed: true
      description: Websites and Services we run
    - name: Network
      closed: true
      description: "Network Services "
    - name: WIFI
      closed: true
      description: WIFI networks and Related Services
    - name: Admin
      closed: true
      description: Admin services
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
